In [1]:
import pandas as pd
from statsbombpy import sb

In [2]:
comps = sb.competitions()
comps.head()

C:\Users\anton\xg-finishing-analysis\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,NaN,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

In [3]:
comps.shape

(80, 12)

In [4]:
comps.columns

Index(['competition_id', 'season_id', 'country_name', 'competition_name',
       'competition_gender', 'competition_youth', 'competition_international',
       'season_name', 'match_updated', 'match_updated_360',
       'match_available_360', 'match_available'],
      dtype='str')

In [5]:
comps["competition_name"].value_counts()

competition_name
Champions League           18
La Liga                    18
FIFA World Cup              8
FA Women's Super League     4
Copa del Rey                3
Ligue 1                     3
1. Bundesliga               2
Liga Profesional            2
NWSL                        2
Premier League              2
Serie A                     2
UEFA Euro                   2
UEFA Women's Euro           2
Women's World Cup           2
African Cup of Nations      1
Copa America                1
FIFA U20 World Cup          1
Frauen Bundesliga           1
Indian Super league         1
Liga F                      1
Major League Soccer         1
North American League       1
Serie A Women               1
UEFA Europa League          1
Name: count, dtype: int64

In [6]:
comps[comps["competition_gender"] == "male"].shape

(67, 12)

In [7]:
la_liga = comps[comps["competition_name"] == "La Liga"]
la_liga[["competition_id", "season_id", "season_name"]]

    competition_id  season_id season_name
40              11         90   2020/2021
41              11         42   2019/2020
42              11          4   2018/2019
43              11          1   2017/2018
44              11          2   2016/2017
45              11         27   2015/2016
46              11         26   2014/2015
47              11         25   2013/2014
48              11         24   2012/2013
49              11         23   2011/2012
50              11         22   2010/2011
51              11         21   2009/2010
52              11         41   2008/2009
53              11         40   2007/2008
54              11         39   2006/2007
55              11         38   2005/2006
56              11         37   2004/2005
57              11        278   1973/1974

In [8]:
matches = sb.matches(competition_id=11, season_id=27)
matches.shape

C:\Users\anton\xg-finishing-analysis\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

(380, 55)

In [9]:
matches["home_team"].value_counts()

home_team
Real Madrid               19
Levante UD                19
Las Palmas                19
RC Deportivo La Coruña    19
Málaga                    19
Espanyol                  19
Sporting Gijón            19
Rayo Vallecano            19
Real Betis                19
Athletic Club             19
Atlético Madrid           19
Valencia                  19
Eibar                     19
Getafe                    19
Villarreal                19
Sevilla                   19
Granada                   19
Real Sociedad             19
Celta Vigo                19
Barcelona                 19
Name: count, dtype: int64

In [10]:
matches_1819 = sb.matches(competition_id=11, season_id=4)
print(matches_1819.shape)
matches_1819["home_team"].value_counts()

C:\Users\anton\xg-finishing-analysis\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

(34, 55)

home_team
Barcelona           18
Real Sociedad        1
Leganés              1
Atlético Madrid      1
Espanyol             1
Sevilla              1
Getafe               1
Real Betis           1
Athletic Club        1
Girona               1
Deportivo Alavés     1
Eibar                1
Levante UD           1
Villarreal           1
Valencia             1
Real Madrid          1
Real Valladolid      1
Name: count, dtype: int64